{% set name = "pdfsyntax" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdfsyntax-{{ version }}.tar.gz
  sha256: 4d4c8654e909a4931e8033e8e03fbd831f97548dea021a000f80b611ef1f75ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - pdfsyntax
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/desgeeko/pdfsyntax
  summary: A Python PDF parsing library and tool built on top to browse the internal structure of a PDF file
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
