{% set name = "pdfsyntax" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdfsyntax-{{ version }}.tar.gz
  sha256: f8570f34eb7feebf685ec8cd55fffeaaeb139c662157e48835c06fe324b9e56d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0
  run:
    - python >=3.8

test:
  imports:
    - pdfsyntax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/desgeeko/pdfsyntax
  summary: A Python PDF parsing library and tool built on top to browse the internal structure of a PDF file
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
