{% set name = "pdfsyntax" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdfsyntax-{{ version }}.tar.gz
  sha256: 93dcfc4e059ccb06a00665cf784f163fa687942dd3067b3e63ef20983952d7d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0
  run:
    - python >=3.8

test:
  imports:
    - pdfsyntax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/desgeeko/pdfsyntax
  summary: A Python PDF parsing library and tool built on top to browse the internal structure of a PDF file
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
