{% set name = "pdfsyntax" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdfsyntax-{{ version }}.tar.gz
  sha256: 60727a969e2251762176cba541a32dce8ec6b8dfa898e101a6fb1a9686bacc48

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=61.0
  run:
    - python >=3.8

test:
  source_files:
    - tests
  imports:
    - pdfsyntax
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not test_all_continuous and not test_all_single and not test_length_continuous and not test_length_single and not test_dict and not test_list and not test_page and not test_page2 and not test_str and not test_index_length and not test_page_list and not test_prev and not test_index_length" tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/desgeeko/pdfsyntax
  summary: A Python PDF parsing library and tool built on top to browse the internal structure of a PDF file
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
